#!/usr/bin/env bash

function usage {
    echo "Usage: cheatwall [OPTIONS] -- [IMAGEMAGIK_OPTIONS]"
}

function main {
    while getopts ":hs:o:i:" opt ; do
	case $opt in
 	    s)
		echo 's'
		;;
 	    i)
		echo 'i'
		;;
 	    o)
		echo 'o'
		;;
 	    h)
		usage
		exit 0
		;;
 	    \?)
		echo "invalaid option: -$OPTARG" >&2
		exit 1
		;;
	    :)
		echo "option -$OPTARG requires an argument" >&2
		exit 1
		;;
	esac
    done
    shift $((OPTIND-1))
    echo "leftover: " "$@"
}

main "$@"
